In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [21]:
clean_job = pd.read_csv('./scrape_data/glints_jobs_clean_final.csv')
clean_job.head(3)

,Judul,Industri,Tipe,Kategori,Tanggal_Post,Berlaku_Hingga,Perusahaan,Website_Perusahaan,Logo_Perusahaan,Alamat,...,Gaji_Currency,Gaji_Unit,Skills,Pengalaman_Bulan,Pendidikan,Deskripsi,Tentang_Perusahaan,Benefit,Apply_Langsung,Link
0,IT Business Analyst,Information Technology and Services,FULL_TIME,System Analyst,2025-04-30T04:48:42.174Z,2026-05-03,PT Venturium System Indonesia,http://www.vensys.co.id,https://images.glints.com/unsafe/glints-dashbo...,JL Utan Kayu Raya No 14,...,Tidak ada,Tidak ada,"SQL, Business Analysis, Relational Databases, ...",36.0,bachelor degree,Job description \n \n Evaluating and documenti...,Tidak ada,Tidak ada,True,https://glints.com/id/opportunities/jobs/it-bu...
1,IT System Analyst,Information Technology and Services,FULL_TIME,System Analyst,2026-03-31T08:57:24.429Z,2026-05-01,Integrasi Optimal Visitama (IOV),https://iov.co.id/,https://images.glints.com/unsafe/glints-dashbo...,Surabaya,...,IDR,MONTH,"Requirements Analysis, SQL, Business Analysis,...",12.0,bachelor degree,General Qualification : \n \n Man (23 - 35 yea...,Integrasi Optimal Visitama (IOV) bergerak dibi...,"medical coverage, bpjs tenaga kerja insurance ...",True,https://glints.com/id/opportunities/jobs/it-sy...
2,IT Business Analyst - Insurance exp,Information Technology and Services,CONTRACTOR,Business Analyst,2025-06-04T04:13:18.761Z,2026-05-06,PT Sigma Global Teknologi,https://www.sigma-tech.co.id,https://images.glints.com/unsafe/glints-dashbo...,"Sona Topas Tower Lt. 12, Jl. Jend. Sudirman, R...",...,IDR,MONTH,"SDLC, Life Insurance, Teamwork, Business Proce...",36.0,bachelor degree,Skill And Experience : \n - Understand the Bas...,SIGMATECH is the enterprise technology partner...,Tidak ada,True,https://glints.com/id/opportunities/jobs/it-bu...

In [22]:
clean_job.columns.tolist()

['Judul',
 'Industri',
 'Tipe',
 'Kategori',
 'Tanggal_Post',
 'Berlaku_Hingga',
 'Perusahaan',
 'Website_Perusahaan',
 'Logo_Perusahaan',
 'Alamat',
 'Kota',
 'Provinsi',
 'Negara',
 'Latitude',
 'Longitude',
 'Gaji_Min',
 'Gaji_Max',
 'Gaji_Currency',
 'Gaji_Unit',
 'Skills',
 'Pengalaman_Bulan',
 'Pendidikan',
 'Deskripsi',
 'Tentang_Perusahaan',
 'Benefit',
 'Apply_Langsung',
 'Link']

In [4]:
clean_job.head(3)

,Judul,Industri,Tipe,Kategori,Tanggal_Post,Berlaku_Hingga,Perusahaan,Website_Perusahaan,Logo_Perusahaan,Alamat,...,Gaji_Currency,Gaji_Unit,Skills,Pengalaman_Bulan,Pendidikan,Deskripsi,Tentang_Perusahaan,Benefit,Apply_Langsung,Link
0,IT Business Analyst,Information Technology and Services,FULL_TIME,System Analyst,2025-04-30T04:48:42.174Z,2026-05-03,PT Venturium System Indonesia,http://www.vensys.co.id,https://images.glints.com/unsafe/glints-dashbo...,JL Utan Kayu Raya No 14,...,Tidak ada,Tidak ada,"SQL, Business Analysis, Relational Databases, ...",36.0,bachelor degree,Job description \n \n Evaluating and documenti...,Tidak ada,Tidak ada,True,https://glints.com/id/opportunities/jobs/it-bu...
1,IT System Analyst,Information Technology and Services,FULL_TIME,System Analyst,2026-03-31T08:57:24.429Z,2026-05-01,Integrasi Optimal Visitama (IOV),https://iov.co.id/,https://images.glints.com/unsafe/glints-dashbo...,Surabaya,...,IDR,MONTH,"Requirements Analysis, SQL, Business Analysis,...",12.0,bachelor degree,General Qualification : \n \n Man (23 - 35 yea...,Integrasi Optimal Visitama (IOV) bergerak dibi...,"medical coverage, bpjs tenaga kerja insurance ...",True,https://glints.com/id/opportunities/jobs/it-sy...
2,IT Business Analyst - Insurance exp,Information Technology and Services,CONTRACTOR,Business Analyst,2025-06-04T04:13:18.761Z,2026-05-06,PT Sigma Global Teknologi,https://www.sigma-tech.co.id,https://images.glints.com/unsafe/glints-dashbo...,"Sona Topas Tower Lt. 12, Jl. Jend. Sudirman, R...",...,IDR,MONTH,"SDLC, Life Insurance, Teamwork, Business Proce...",36.0,bachelor degree,Skill And Experience : \n - Understand the Bas...,SIGMATECH is the enterprise technology partner...,Tidak ada,True,https://glints.com/id/opportunities/jobs/it-bu...

#### Membuang kolom tidak penting untuk tujuan Modeling

In [23]:
# remove kolom tidak penting
deleted_columns = [
    'Tanggal_Post', 
    'Berlaku_Hingga', 
    'Perusahaan', 
    'Website_Perusahaan', 
    'Logo_Perusahaan', 
    'Alamat', 
    'Latitude',
    'Longitude',
    'Gaji_Currency',
    'Gaji_Unit',
    'Tentang_Perusahaan',
    'Benefit',
    'Apply_Langsung',
    'Link'
]

df_1 = clean_job.copy()
df_2 = clean_job.copy()

# hapus kolom yang tidak penting
df_1.drop(columns=deleted_columns, inplace=True)
df_1.columns.to_list()

['Judul',
 'Industri',
 'Tipe',
 'Kategori',
 'Kota',
 'Provinsi',
 'Negara',
 'Gaji_Min',
 'Gaji_Max',
 'Skills',
 'Pengalaman_Bulan',
 'Pendidikan',
 'Deskripsi']

In [24]:
# cek apakah ada duplicate
df_1.duplicated().sum()

np.int64(158)

In [25]:
df_2.duplicated().sum()

np.int64(0)

In [26]:
mask_duplicate = df_1.duplicated()

# hapus duplicate
df_1 = df_1[~mask_duplicate]

df_2 = df_2[~mask_duplicate]

df_2.columns.to_list()

['Judul',
 'Industri',
 'Tipe',
 'Kategori',
 'Tanggal_Post',
 'Berlaku_Hingga',
 'Perusahaan',
 'Website_Perusahaan',
 'Logo_Perusahaan',
 'Alamat',
 'Kota',
 'Provinsi',
 'Negara',
 'Latitude',
 'Longitude',
 'Gaji_Min',
 'Gaji_Max',
 'Gaji_Currency',
 'Gaji_Unit',
 'Skills',
 'Pengalaman_Bulan',
 'Pendidikan',
 'Deskripsi',
 'Tentang_Perusahaan',
 'Benefit',
 'Apply_Langsung',
 'Link']

In [27]:
df_1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2761 entries, 0 to 2918
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Judul             2761 non-null   object
 1   Industri          2761 non-null   object
 2   Tipe              2761 non-null   object
 3   Kategori          2761 non-null   object
 4   Kota              2761 non-null   object
 5   Provinsi          2761 non-null   object
 6   Negara            2761 non-null   object
 7   Gaji_Min          2761 non-null   object
 8   Gaji_Max          2761 non-null   object
 9   Skills            2761 non-null   object
 10  Pengalaman_Bulan  2761 non-null   object
 11  Pendidikan        2761 non-null   object
 12  Deskripsi         2761 non-null   object
dtypes: object(13)
memory usage: 302.0+ KB

In [28]:
df_2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2761 entries, 0 to 2918
Data columns (total 27 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Judul               2761 non-null   object
 1   Industri            2761 non-null   object
 2   Tipe                2761 non-null   object
 3   Kategori            2761 non-null   object
 4   Tanggal_Post        2761 non-null   object
 5   Berlaku_Hingga      2761 non-null   object
 6   Perusahaan          2761 non-null   object
 7   Website_Perusahaan  2761 non-null   object
 8   Logo_Perusahaan     2761 non-null   object
 9   Alamat              2761 non-null   object
 10  Kota                2761 non-null   object
 11  Provinsi            2761 non-null   object
 12  Negara              2761 non-null   object
 13  Latitude            2761 non-null   object
 14  Longitude           2761 non-null   object
 15  Gaji_Min            2761 non-null   object
 16  Gaji_Max            2761 non-null   object
 17  Gaji_Currency       2761 non-null   object
 18  Gaji_Unit           2761 non-null   object
 19  Skills              2761 non-null   object
 20  Pengalaman_Bulan    2761 non-null   object
 21  Pendidikan          2761 non-null   object
 22  Deskripsi           2761 non-null   object
 23  Tentang_Perusahaan  2761 non-null   object
 24  Benefit             2761 non-null   object
 25  Apply_Langsung      2761 non-null   object
 26  Link                2761 non-null   object
dtypes: object(27)
memory usage: 604.0+ KB

In [31]:
print(df_1.isnull().sum())
print(df_2.isnull().sum())

print(df_1.duplicated().sum())
print(df_2.duplicated().sum())

Judul               0
Industri            0
Tipe                0
Kategori            0
Kota                0
Provinsi            0
Negara              0
Gaji_Min            0
Gaji_Max            0
Skills              0
Pengalaman_Bulan    0
Pendidikan          0
Deskripsi           0
dtype: int64
Judul                 0
Industri              0
Tipe                  0
Kategori              0
Tanggal_Post          0
Berlaku_Hingga        0
Perusahaan            0
Website_Perusahaan    0
Logo_Perusahaan       0
Alamat                0
Kota                  0
Provinsi              0
Negara                0
Latitude              0
Longitude             0
Gaji_Min              0
Gaji_Max              0
Gaji_Currency         0
Gaji_Unit             0
Skills                0
Pengalaman_Bulan      0
Pendidikan            0
Deskripsi             0
Tentang_Perusahaan    0
Benefit               0
Apply_Langsung        0
Link                  0
dtype: int64
0
0

In [32]:
# masih membutuhkan index sepertinya, jadi tidak perlu drop index
df_1.to_csv('data_untuk_modeling.csv', index=True)
df_2.to_csv('data_untuk_raw_backend.csv', index=True)

### Mencari Data Untuk Database FS